name: 🐞 Bug report
description: If you found something that we should know about.
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Please answer the following questions for yourself before submitting an issue
      options:
        - label: Filters were updated before reproducing an issue
          required: true
        - label: I checked the [knowledge base](https://adguard.com/kb/) and found no answer
          required: true
        - label: I checked to make sure that this issue has not already been filed
          required: true
  - type: input
    id: app_version
    attributes:
      label: AdGuard MV3 Extension version
      description: What version of our extension are you running?
      placeholder: For example, 0.4.48
    validations:
      required: true
  - type: input
    id: br_version
    attributes:
      label: Browser version
      description: What browser do you use?
      placeholder: For example, Chrome 123
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: OS version
      description: What operating system do you use?
      placeholder: For example, macOS 14.5
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### What filters do you have enabled?"

  - type: markdown
    attributes:
      value: |
        Select enabled filters if they are related to the application bug.
        If the issue is related to the filtering (missed ads, cookie, etc.)
        use the [Web Reporting Tool](https://kb.adguard.com/technical-support/reporting-tool) please.
        
  - type: dropdown
    id: filters
    attributes:
      label: Filters enabled
      multiple: true
      options:
        - Block ads
        - Block annoyances
        - Block trackers
        - Block social widgets
        - ---Language-specific filters---
        - English
        - Russian
        - German
        - Japanese
        - Dutch
        - Spanish/Portuguese
        - Turkish
        - French
        - Chinese
    validations:
      required: false
  
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Details
      description: Please provide a set of steps to reproduce the issue.
      placeholder:
      value: |
        Steps to reproduce:
        1.
        2.
        3.
    validations:
      required: true
      
  - type: textarea
    id: how_it_should_be
    attributes:
      label: Expected Behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: false
      
  - type: textarea
    id: how_it_is
    attributes:
      label: Actual Behavior
      placeholder: A clear description of what happened instead.
    validations:
      required: true
      
  - type: textarea
    id: screens
    attributes:
      label: Screenshots
      description: |
        If applicable add screenshots explaining your problem.
        You can drag and drop images or paste them from clipboard.
        Use `<details> </details>` tag to hide screenshots under the spoiler.
      placeholder: If applicable add screenshots explaining your problem.
      value: |
          <details><summary>Screenshot 1</summary>

          <!-- paste screenshot here -->

          </details>
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      placeholder: Add any other context about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        Upvote [important issues](https://github.com/AdguardTeam/AdGuardMV3/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+) with a :+1: