export const MESSAGE_TYPES = {
    GET_PROTECTION_ENABLED: 'GET_PROTECTION_ENABLED',
    SET_PROTECTION_ENABLED: 'SET_PROTECTION_ENABLED',
    GET_CSS: 'GET_CSS',
    OPEN_OPTIONS: 'OPEN_OPTIONS',
} as const;

export const PROTECTION_ENABLED_KEY = 'protection.enabled';
